export interface Ward {
  id: number;
  name: string;
  zone: string;
}

export const DELHI_WARDS: Ward[] = [
  { id: 1, name: "NARELA", zone: "Narela" },
  { id: 2, name: "BANKNER", zone: "Narela" },
  { id: 3, name: "HOLAMBI KALAN", zone: "Narela" },
  { id: 4, name: "ALIPUR", zone: "Narela" },
  { id: 5, name: "BAKHTAWARPUR", zone: "Narela" },
  { id: 26, name: "POOTH KALAN", zone: "Narela" },
  { id: 27, name: "BEGUMPUR", zone: "Narela" },
  { id: 28, name: "SHAHBAAD DAIRY", zone: "Narela" },
  { id: 29, name: "POOTH KHURD", zone: "Narela" },
  { id: 30, name: "BAWANA", zone: "Narela" },
  { id: 31, name: "NANGAL THAKRAN", zone: "Narela" },
  { id: 32, name: "KANJHAWALA", zone: "Narela" },
  { id: 33, name: "RANI KHERA", zone: "Narela" },
  { id: 34, name: "NANGLOI", zone: "Narela" },
  { id: 35, name: "MUNDKA", zone: "Narela" },
  { id: 36, name: "NILOTHI", zone: "Narela" },
  { id: 6, name: "BURARI", zone: "Civil Line" },
  { id: 7, name: "KADIPUR", zone: "Civil Line" },
  { id: 8, name: "MUKUNDPUR", zone: "Civil Line" },
  { id: 9, name: "SANT NAGAR", zone: "Civil Line" },
  { id: 10, name: "JHARODA", zone: "Civil Line" },
  { id: 11, name: "TIMARPUR", zone: "Civil Line" },
  { id: 12, name: "MALKA GANJ", zone: "Civil Line" },
  { id: 13, name: "MUKHERJEE NAGAR", zone: "Civil Line" },
  { id: 14, name: "DHIRPUR", zone: "Civil Line" },
  { id: 15, name: "ADARSH NAGAR", zone: "Civil Line" },
  { id: 16, name: "AZADPUR", zone: "Civil Line" },
  { id: 17, name: "BHALSWA", zone: "Civil Line" },
  { id: 18, name: "JAHANGIR PURI", zone: "Civil Line" },
  { id: 19, name: "SARUP NAGAR", zone: "Civil Line" },
  { id: 20, name: "SAMAYPUR BADLI", zone: "Civil Line" },
  { id: 21, name: "ROHINI-A", zone: "Rohini" },
  { id: 22, name: "ROHINI-B", zone: "Rohini" },
  { id: 23, name: "RITHALA", zone: "Rohini" },
  { id: 24, name: "VIJAY VIHAR", zone: "Rohini" },
  { id: 25, name: "BUDH VIHAR", zone: "Rohini" },
  { id: 37, name: "KIRARI", zone: "Rohini" },
  { id: 38, name: "PREM NAGAR", zone: "Rohini" },
  { id: 39, name: "MUBARIKPUR", zone: "Rohini" },
  { id: 40, name: "NITHARI", zone: "Rohini" },
  { id: 41, name: "AMAN VIHAR", zone: "Rohini" },
  { id: 42, name: "MANGOL PURI", zone: "Rohini" },
  { id: 43, name: "SULTANPURI-A", zone: "Rohini" },
  { id: 44, name: "SULTANPURI-B", zone: "Rohini" },
  { id: 45, name: "JAWALAPURI", zone: "Rohini" },
  { id: 46, name: "NANGLOI JAT", zone: "Rohini" },
  { id: 47, name: "NIHAL VIHAR", zone: "Rohini" },
  { id: 48, name: "GURU HARKISHAN NAGAR", zone: "Rohini" },
  { id: 49, name: "MANGOLPURI-A", zone: "Rohini" },
  { id: 50, name: "MANGOLPURI-B", zone: "Rohini" },
  { id: 51, name: "ROHINI-C", zone: "Rohini" },
  { id: 52, name: "ROHINI-F", zone: "Rohini" },
  { id: 53, name: "ROHINI-E", zone: "Rohini" },
  { id: 54, name: "ROHINI-D", zone: "Rohini" },
  { id: 55, name: "SHALIMAR BAGH-A", zone: "Keshavpuram" },
  { id: 56, name: "SHALIMAR BAGH-B", zone: "Keshavpuram" },
  { id: 57, name: "PITAM PURA", zone: "Keshavpuram" },
  { id: 58, name: "SARASWATI VIHAR", zone: "Keshavpuram" },
  { id: 59, name: "PASCHIM VIHAR", zone: "Keshavpuram" },
  { id: 60, name: "RANI BAGH", zone: "Keshavpuram" },
  { id: 61, name: "KOHAT ENCLAVE", zone: "Keshavpuram" },
  { id: 62, name: "SHAKUR PUR", zone: "Keshavpuram" },
  { id: 63, name: "TRI NAGAR", zone: "Keshavpuram" },
  { id: 64, name: "KESHAV PURAM", zone: "Keshavpuram" },
  { id: 65, name: "ASHOK VIHAR", zone: "Keshavpuram" },
  { id: 66, name: "WAZIR PUR", zone: "Keshavpuram" },
  { id: 67, name: "SANGAM PARK", zone: "Keshavpuram" },
  { id: 68, name: "MODEL TOWN", zone: "Keshavpuram" },
  { id: 69, name: "KAMLA NAGAR", zone: "Keshavpuram" },
  { id: 70, name: "SHASTRI NAGAR", zone: "City S.P.Zone" },
  { id: 71, name: "KISHAN GANJ", zone: "City S.P.Zone" },
  { id: 72, name: "SADAR BAZAR", zone: "City S.P.Zone" },
  { id: 73, name: "CIVIL LINES", zone: "City S.P.Zone" },
  { id: 74, name: "CHANDNI CHOWK", zone: "City S.P.Zone" },
  { id: 75, name: "JAMA MASJID", zone: "City S.P.Zone" },
  { id: 76, name: "CHANDANI MAHAL", zone: "City S.P.Zone" },
  { id: 77, name: "DELHI GATE", zone: "City S.P.Zone" },
  { id: 78, name: "BAZAR SITA RAM", zone: "City S.P.Zone" },
  { id: 79, name: "BALLIMARAN", zone: "City S.P.Zone" },
  { id: 80, name: "RAM NAGAR", zone: "City S.P.Zone" },
  { id: 81, name: "QURAISH NAGAR", zone: "City S.P.Zone" },
  { id: 82, name: "PAHAR GANJ", zone: "Karolbagh" },
  { id: 83, name: "KAROL BAGH", zone: "Karolbagh" },
  { id: 84, name: "DEV NAGAR", zone: "Karolbagh" },
  { id: 85, name: "WEST PATEL NAGAR", zone: "Karolbagh" },
  { id: 86, name: "EAST PATEL NAGAR", zone: "Karolbagh" },
  { id: 87, name: "RANJEET NAGAR", zone: "Karolbagh" },
  { id: 88, name: "BALJEET NAGAR", zone: "Karolbagh" },
  { id: 89, name: "KARAM PURA", zone: "Karolbagh" },
  { id: 90, name: "MOTI NAGAR", zone: "Karolbagh" },
  { id: 91, name: "RAMESH NAGAR", zone: "Karolbagh" },
  { id: 139, name: "NARAINA", zone: "Karolbagh" },
  { id: 140, name: "INDER PURI", zone: "Karolbagh" },
  { id: 141, name: "RAJINDER NAGAR", zone: "Karolbagh" },
  { id: 92, name: "PUNJABI BAGH", zone: "West Zone" },
  { id: 93, name: "MADIPUR", zone: "West Zone" },
  { id: 94, name: "RAGHUBIR NAGAR", zone: "West Zone" },
  { id: 95, name: "VISHNU GARDEN", zone: "West Zone" },
  { id: 96, name: "RAJOURI GARDEN", zone: "West Zone" },
  { id: 97, name: "CHAUKHANDI NAGAR", zone: "West Zone" },
  { id: 98, name: "SUBHASH NAGAR", zone: "West Zone" },
  { id: 99, name: "HARI NAGAR", zone: "West Zone" },
  { id: 100, name: "FATEH NAGAR", zone: "West Zone" },
  { id: 101, name: "TILAK NAGAR", zone: "West Zone" },
  { id: 102, name: "KHYALA", zone: "West Zone" },
  { id: 103, name: "KESHOPUR", zone: "West Zone" },
  { id: 104, name: "JANAK PURI SOUTH", zone: "West Zone" },
  { id: 105, name: "MAHAVEER ENCLAVE", zone: "West Zone" },
  { id: 106, name: "JANAK PURI WEST", zone: "West Zone" },
  { id: 107, name: "VIKAS PURI", zone: "West Zone" },
  { id: 108, name: "HASTSAL", zone: "West Zone" },
  { id: 109, name: "VIKAS NAGAR", zone: "West Zone" },
  { id: 110, name: "KUNWAR SINGH NAGAR", zone: "West Zone" },
  { id: 111, name: "BAPROLA", zone: "West Zone" },
  { id: 112, name: "SAINIK ENCLAVE", zone: "West Zone" },
  { id: 113, name: "MOHAN GARDEN", zone: "West Zone" },
  { id: 114, name: "NAWADA", zone: "West Zone" },
  { id: 115, name: "UTTAM NAGAR", zone: "West Zone" },
  { id: 116, name: "BINDA PUR", zone: "West Zone" },
  { id: 117, name: "DABRI", zone: "Najafgarh Zone" },
  { id: 118, name: "SAGARPUR", zone: "Najafgarh Zone" },
  { id: 119, name: "MANGLAPURI", zone: "Najafgarh Zone" },
  { id: 120, name: "DWARKA-B", zone: "Najafgarh Zone" },
  { id: 121, name: "DWARKA-A", zone: "Najafgarh Zone" },
  { id: 122, name: "MATIALA", zone: "Najafgarh Zone" },
  { id: 123, name: "KAKROLA", zone: "Najafgarh Zone" },
  { id: 124, name: "NANGLI SAKRAWATI", zone: "Najafgarh Zone" },
  { id: 125, name: "CHHAWALA", zone: "Najafgarh Zone" },
  { id: 126, name: "ISAPUR", zone: "Najafgarh Zone" },
  { id: 127, name: "NAJAFGARH", zone: "Najafgarh Zone" },
  { id: 128, name: "DICHAON KALAN", zone: "Najafgarh Zone" },
  { id: 129, name: "ROSHAN PURA", zone: "Najafgarh Zone" },
  { id: 130, name: "DWARKA-C", zone: "Najafgarh Zone" },
  { id: 131, name: "BIJWASAN", zone: "Najafgarh Zone" },
  { id: 132, name: "KAPASHERA", zone: "Najafgarh Zone" },
  { id: 133, name: "MAHIPALPUR", zone: "Najafgarh Zone" },
  { id: 134, name: "RAJ NAGAR", zone: "Najafgarh Zone" },
  { id: 135, name: "PALAM", zone: "Najafgarh Zone" },
  { id: 136, name: "MADHU VIHAR", zone: "Najafgarh Zone" },
  { id: 137, name: "MAHAVIR ENCLAVE", zone: "Najafgarh Zone" },
  { id: 138, name: "SADH NAGAR", zone: "Najafgarh Zone" },
  { id: 142, name: "DARYAGANJ", zone: "Central Zone" },
  { id: 143, name: "SIDHARTHA NAGAR", zone: "Central Zone" },
  { id: 144, name: "LAJPAT NAGAR", zone: "Central Zone" },
  { id: 145, name: "ANDREWS GANJ", zone: "Central Zone" },
  { id: 146, name: "AMAR COLONY", zone: "Central Zone" },
  { id: 147, name: "KOTLA MUBARAKPUR", zone: "Central Zone" },
  { id: 168, name: "SANGAM VIHAR-C", zone: "Central Zone" },
  { id: 169, name: "SANGAM VIHAR-B", zone: "Central Zone" },
  { id: 170, name: "TUGHLAKABAD EXTENSION", zone: "Central Zone" },
  { id: 174, name: "SRI NIWAS PURI", zone: "Central Zone" },
  { id: 175, name: "KALKAJI", zone: "Central Zone" },
  { id: 176, name: "GOVIND PURI", zone: "Central Zone" },
  { id: 177, name: "HARKESH NAGAR", zone: "Central Zone" },
  { id: 178, name: "TUGHLAKABAD", zone: "Central Zone" },
  { id: 179, name: "PUL PEHLADPUR", zone: "Central Zone" },
  { id: 180, name: "BADARPUR", zone: "Central Zone" },
  { id: 181, name: "MOLARBAND", zone: "Central Zone" },
  { id: 182, name: "MEETHAPUR", zone: "Central Zone" },
  { id: 183, name: "HARI NAGAR EXTENSION", zone: "Central Zone" },
  { id: 184, name: "JAITPUR", zone: "Central Zone" },
  { id: 185, name: "MADANPUR KHADAR EAST", zone: "Central Zone" },
  { id: 186, name: "MADANPUR KHADAR WEST", zone: "Central Zone" },
  { id: 187, name: "SARITA VIHAR", zone: "Central Zone" },
  { id: 188, name: "ABUL FAZAL ENCLAVE", zone: "Central Zone" },
  { id: 189, name: "ZAKIR NAGAR", zone: "Central Zone" },
  { id: 148, name: "HAUZ KHAS", zone: "South Zone" },
  { id: 149, name: "MALVIYA NAGAR", zone: "South Zone" },
  { id: 150, name: "GREEN PARK", zone: "South Zone" },
  { id: 151, name: "MUNIRKA", zone: "South Zone" },
  { id: 152, name: "R.K. PURAM", zone: "South Zone" },
  { id: 153, name: "VASANT VIHAR", zone: "South Zone" },
  { id: 154, name: "LADO SARAI", zone: "South Zone" },
  { id: 155, name: "MEHRAULI", zone: "South Zone" },
  { id: 156, name: "VASANT KUNJ", zone: "South Zone" },
  { id: 157, name: "AYA NAGAR", zone: "South Zone" },
  { id: 158, name: "BHATI", zone: "South Zone" },
  { id: 159, name: "CHHATARPUR", zone: "South Zone" },
  { id: 160, name: "SAID-UL-AJAIB", zone: "South Zone" },
  { id: 161, name: "DEOLI", zone: "South Zone" },
  { id: 162, name: "TIGRI", zone: "South Zone" },
  { id: 163, name: "SANGAM VIHAR-A", zone: "South Zone" },
  { id: 164, name: "DAKSHIN PURI", zone: "South Zone" },
  { id: 165, name: "MADANGIR", zone: "South Zone" },
  { id: 166, name: "PUSHP VIHAR", zone: "South Zone" },
  { id: 167, name: "KHANPUR", zone: "South Zone" },
  { id: 171, name: "CHITARANJAN PARK", zone: "South Zone" },
  { id: 172, name: "CHIRAG DELHI", zone: "South Zone" },
  { id: 173, name: "GREATER KAILASH", zone: "South Zone" },
  { id: 190, name: "NEW ASHOK NAGAR", zone: "Shahdara South Zone" },
  { id: 191, name: "MAYUR VIHAR PHASE-I", zone: "Shahdara South Zone" },
  { id: 192, name: "TRILOKPURI", zone: "Shahdara South Zone" },
  { id: 193, name: "KONDLI", zone: "Shahdara South Zone" },
  { id: 194, name: "GHAROLI", zone: "Shahdara South Zone" },
  { id: 195, name: "KALYANPURI", zone: "Shahdara South Zone" },
  { id: 196, name: "MAYUR VIHAR PHASE-II", zone: "Shahdara South Zone" },
  { id: 197, name: "PATPAR GANJ", zone: "Shahdara South Zone" },
  { id: 198, name: "VINOD NAGAR", zone: "Shahdara South Zone" },
  { id: 199, name: "MANDAWALI", zone: "Shahdara South Zone" },
  { id: 200, name: "PANDAV NAGAR", zone: "Shahdara South Zone" },
  { id: 201, name: "LALITA PARK", zone: "Shahdara South Zone" },
  { id: 202, name: "SHAKARPUR", zone: "Shahdara South Zone" },
  { id: 203, name: "LAXMI NAGAR", zone: "Shahdara South Zone" },
  { id: 204, name: "PREET VIHAR", zone: "Shahdara South Zone" },
  { id: 205, name: "I.P. EXTENSION", zone: "Shahdara South Zone" },
  { id: 206, name: "ANAND VIHAR", zone: "Shahdara South Zone" },
  { id: 207, name: "VISHWAS NAGAR", zone: "Shahdara South Zone" },
  { id: 208, name: "ANARKALI", zone: "Shahdara South Zone" },
  { id: 209, name: "JAGAT PURI", zone: "Shahdara South Zone" },
  { id: 210, name: "GEETA COLONY", zone: "Shahdara South Zone" },
  { id: 211, name: "KRISHNA NAGAR", zone: "Shahdara South Zone" },
  { id: 212, name: "GANDHI NAGAR", zone: "Shahdara South Zone" },
  { id: 213, name: "SHASTRI PARK", zone: "Shahdara South Zone" },
  { id: 214, name: "AZAD NAGAR", zone: "Shahdara South Zone" },
  { id: 215, name: "SHAHDARA", zone: "Shahdara South Zone" },
  { id: 216, name: "JHILMIL", zone: "Shahdara North Zone" },
  { id: 217, name: "DILSHAD COLONY", zone: "Shahdara North Zone" },
  { id: 218, name: "SUNDAR NAGRI", zone: "Shahdara North Zone" },
  { id: 219, name: "DILSHAD GARDEN", zone: "Shahdara North Zone" },
  { id: 220, name: "NAND NAGRI", zone: "Shahdara North Zone" },
  { id: 221, name: "ASHOK NAGAR", zone: "Shahdara North Zone" },
  { id: 222, name: "RAM NAGAR EAST", zone: "Shahdara North Zone" },
  { id: 223, name: "ROHTASH NAGAR", zone: "Shahdara North Zone" },
  { id: 224, name: "WELCOME COLONY", zone: "Shahdara North Zone" },
  { id: 225, name: "SEELAMPUR", zone: "Shahdara North Zone" },
  { id: 226, name: "GAUTAM PURI", zone: "Shahdara North Zone" },
  { id: 227, name: "CHAUHAN BANGER", zone: "Shahdara North Zone" },
  { id: 228, name: "MAUJPUR", zone: "Shahdara North Zone" },
  { id: 229, name: "BRAHAM PURI", zone: "Shahdara North Zone" },
  { id: 230, name: "BHAJANPURA", zone: "Shahdara North Zone" },
  { id: 231, name: "GHONDA", zone: "Shahdara North Zone" },
  { id: 232, name: "YAMUNA VIHAR", zone: "Shahdara North Zone" },
  { id: 233, name: "SUBHASH MOHALLA", zone: "Shahdara North Zone" },
  { id: 234, name: "KABIR NAGAR", zone: "Shahdara North Zone" },
  { id: 235, name: "GORAKH PARK", zone: "Shahdara North Zone" },
  { id: 236, name: "KARDAM PURI", zone: "Shahdara North Zone" },
  { id: 237, name: "HARSH VIHAR", zone: "Shahdara North Zone" },
  { id: 238, name: "SABOLI", zone: "Shahdara North Zone" },
  { id: 239, name: "GOKAL PURI", zone: "Shahdara North Zone" },
  { id: 240, name: "JOHARIPUR", zone: "Shahdara North Zone" },
  { id: 241, name: "KARAWAL NAGAR-EAST", zone: "Shahdara North Zone" },
  { id: 242, name: "DAYALPUR", zone: "Shahdara North Zone" },
  { id: 243, name: "MUSTAFABAD", zone: "Shahdara North Zone" },
  { id: 244, name: "NEHRU VIHAR", zone: "Shahdara North Zone" },
  { id: 245, name: "BRIJ PURI", zone: "Shahdara North Zone" },
  { id: 246, name: "SRI RAM COLONY", zone: "Shahdara North Zone" },
  { id: 247, name: "SADATPUR", zone: "Shahdara North Zone" },
  { id: 248, name: "KARAWAL NAGAR-WEST", zone: "Shahdara North Zone" },
  { id: 249, name: "SONIA VIHAR", zone: "Shahdara North Zone" },
  { id: 250, name: "SABAPUR", zone: "Shahdara" },
];
